sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - uuid-dev
    - libssl-dev
language: node_js
node_js:
- '5'
env:
  global:
  - ZMQ="3.2.5"
  - secure: 322RGbn3C8LZ9u6HlKPDKvD/YyMz/fmvnizV5LAgtMt07+421cfLG+XlWurlxIdyytKI6i/ynz1cxPcG3wWSi7GCa7DNbQ/3LbmeeKm9n4+HGcdiOjnzGYpp9Dm8n1l6VDNwUNcwZLjCDdgWKU3GSEr9euayJ+CgVtC8tYGdmbEBFnfuoDbHHmTqwW5n7h5mKsra78TrsVbSE6flA3DYtrm0/glaTCg7RgqZumrly/zi45n0KswUp2ugzU+aFZ0q01xmPvsxaYxMQkSUhSym3p+Ftz0gtJsOjBAun+n2osMuSbrrnW3A7s5T4agxONCUZNg76/11T6n8A2MhlQ1XQE5VHefBiJb6dFcmkCzhBXomJZr6NnEVlgy6GEiuaOG9gd9OOx1WGdBCyv1Pd9QSGwHNxz09IHwV4imvV5JYTQJ5NSpgYA9ZyfdZAwWiC1tLkd553ePBza/hS0vr1ozc4Im6WF0hier1h7mXyZDLA9cpvgBTYuNJYdTwy9tft5rTLm76BLRPOU6TpcgcgRlkj4e+kuzXI2n9r1F1OmsNPllxqyT0UbUyox8LOpmogRl/x0FyH308zDTZjqyM8jFzwhEJh8kf6dkFHOOjIFzVZ33OM+NaSd3hWNdA0yyYX6uHTnWohgBgiNxPlOrXARpneMMezssF/dlm6fKRgV+aES8=
  matrix:
  - GROUP=unit
  - GROUP=functional
before_install:
  - source travis_before_install

install: env LD_LIBRARY_PATH=$LDHACK/lib LD_RUN_PATH=$LDHACK/lib PKG_CONFIG_PATH=$LDHACK/lib/pkgconfig LDFLAGS=-L$LDHACK/lib CFLAGS=-I$LDHACK/lib/include npm install

before_script:
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script: travis_retry npm run test:$GROUP
after_success: npm run coverage
